### ISSUE TITLE
Wish to hava clear and downloadable deck preview .jpg file 

### ISSUE THREAD

**Issue by Jeffbase** [relax100002000/WIXOSS_deckeditor#1]
Right now the deck preview is responsive with user, and cannot see exactly the name of card(very unclear). 
Overall is very impressive, very excited for later version.

**Comment by relax100002000** [comment]
Hi Jeffbase,

I appreciate your feedback and try to rework the "Deck View" function to ensure every card name will be recognize.

Thank for your feedback and if you have any suggestion, please let me know.
